### ISSUE TITLE
merge conflict leftovers in sppEquivalencies_CA.csv

### ISSUE THREAD

**Issue by suz-estella** [PredictiveEcology/LandR#169]
@pkalanta I suspect you may have committed a merge conflict to the sppEquivalencies_CA table in the development branch: https://github.com/predictiveecology/LandR/blob/1a068021a70aee38bb35beec377bcf6bd7574d1d/data-raw/sppEquivalencies_CA.csv#L1

I gave it a try to read & reformat it myself but it wasn't as straightforward as I hoped since the other columns seem to differ from the most recent version here: https://github.com/predictiveecology/LandR/blob/27a9cfccc830516557dcf957ed91dfd342a9d574/data-raw/sppEquivalencies_CA.csv

For example, I'm not seeing the "CanfiCode" column in your table.

Happy to try to help :)

**Comment by pkalanta** [comment]
Susan, I’ve fixed the merge conflict in sppEquivalencies_CA.csv and pushed it to development. The SK_Forestry updates are included, you can pull the branch now.
Thanks,

**Comment by suz-estella** [comment]
The table definitely looks in better shape! I do notice that the "CanfiCode" column is still missing which is one of the ones that we use. Admittedly, it would be better for us to be building our modules off the main branch but that's not possible yet.

Is it possible your version of the table is an edit of the main branch CSV instead of the development one? The "CanfiCode" column is not there either.

**Comment by pkalanta** [comment]
Thanks for checking , you’re right, the “CanfiCode” column is missing in the version I pushed. I have it in my local CSV, so I’ll add it to the file on the development branch and push the updated version shortly.
That should ensure all the necessary columns are present while keeping the SK_Forestry edits.
Thanks,

**Comment by suz-estella** [comment]
@ianmseddy do you want to have a look at this before closing?
